export const countries = [
  { value: "AFG", label: "Afghanistan" },
  { value: "ALB", label: "Albania" },
  { value: "DZA", label: "Algeria" },
  { value: "ASM", label: "American Samoa" },
  { value: "ADO", label: "Andorra" },
  { value: "AGO", label: "Angola" },
  { value: "ATG", label: "Antigua and Barbuda" },
  { value: "ARB", label: "Arab World" },
  { value: "ARG", label: "Argentina" },
  { value: "ARM", label: "Armenia" },
  { value: "ABW", label: "Aruba" },
  { value: "AUS", label: "Australia" },
  { value: "AUT", label: "Austria" },
  { value: "AZE", label: "Azerbaijan" },
  { value: "BHR", label: "Bahrain" },
  { value: "BGD", label: "Bangladesh" },
  { value: "BRB", label: "Barbados" },
  { value: "BLR", label: "Belarus" },
  { value: "BEL", label: "Belgium" },
  { value: "BLZ", label: "Belize" },
  { value: "BEN", label: "Benin" },
  { value: "BMU", label: "Bermuda" },
  { value: "BTN", label: "Bhutan" },
  { value: "BOL", label: "Bolivia" },
  { value: "BIH", label: "Bosnia and Herzegovina" },
  { value: "BWA", label: "Botswana" },
  { value: "BRA", label: "Brazil" },
  { value: "BRN", label: "Brunei" },
  { value: "BGR", label: "Bulgaria" },
  { value: "BFA", label: "Burkina Faso" },
  { value: "BDI", label: "Burundi" },
  { value: "CPV", label: "Cabo Verde" },
  { value: "KHM", label: "Cambodia" },
  { value: "CMR", label: "Cameroon" },
  { value: "CAN", label: "Canada" },
  { value: "CSS", label: "Caribbean small states" },
  { value: "CYM", label: "Cayman Islands" },
  { value: "CAF", label: "Central African Republic" },
  { value: "CEB", label: "Central Europe and the Baltics" },
  { value: "TCD", label: "Chad" },
  { value: "CHI", label: "Channel Islands" },
  { value: "CHL", label: "Chile" },
  { value: "CHN", label: "China" },
  { value: "COL", label: "Colombia" },
  { value: "COM", label: "Comoros" },
  { value: "COG", label: "Congo" },
  { value: "CRI", label: "Costa Rica" },
  { value: "HRV", label: "Croatia" },
  { value: "CUB", label: "Cuba" },
  { value: "CUW", label: "Curaçao" },
  { value: "CYP", label: "Cyprus" },
  { value: "CZE", label: "Czech Republic" },
  { value: "CIV", label: "Côte d'Ivoire" },
  { value: "PRK", label: "Dem. People's Rep. Korea" },
  { value: "ZAR", label: "Dem. Rep. Congo" },
  { value: "DNK", label: "Denmark" },
  { value: "DJI", label: "Djibouti" },
  { value: "DMA", label: "Dominica" },
  { value: "DOM", label: "Dominican Republic" },
  { value: "EAS", label: "East Asia & Pacific (all income levels)" },
  { value: "EAP", label: "East Asia & Pacific (developing only)" },
  { value: "ECU", label: "Ecuador" },
  { value: "EGY", label: "Egypt" },
  { value: "SLV", label: "El Salvador" },
  { value: "GNQ", label: "Equatorial Guinea" },
  { value: "ERI", label: "Eritrea" },
  { value: "EST", label: "Estonia" },
  { value: "ETH", label: "Ethiopia" },
  { value: "EMU", label: "Euro area" },
  { value: "ECS", label: "Europe & Central Asia (all income levels)" },
  { value: "ECA", label: "Europe & Central Asia (developing only)" },
  { value: "EUU", label: "European Union" },
  { value: "FRO", label: "Faeroe Islands" },
  { value: "FJI", label: "Fiji" },
  { value: "FIN", label: "Finland" },
  { value: "FCS", label: "Fragile and conflict affected situations" },
  { value: "FRA", label: "France" },
  { value: "PYF", label: "French Polynesia" },
  { value: "GAB", label: "Gabon" },
  { value: "GEO", label: "Georgia" },
  { value: "DEU", label: "Germany" },
  { value: "GHA", label: "Ghana" },
  { value: "GRC", label: "Greece" },
  { value: "GRL", label: "Greenland" },
  { value: "GRD", label: "Grenada" },
  { value: "GUM", label: "Guam" },
  { value: "GTM", label: "Guatemala" },
  { value: "GIN", label: "Guinea" },
  { value: "GNB", label: "Guinea-Bissau" },
  { value: "GUY", label: "Guyana" },
  { value: "HTI", label: "Haiti" },
  { value: "HPC", label: "Heavily indebted poor countries (HIPC)" },
  { value: "HIC", label: "High income" },
  { value: "OEC", label: "High income: OECD" },
  { value: "NOC", label: "High income: nonOECD" },
  { value: "HND", label: "Honduras" },
  { value: "HKG", label: "Hong Kong SAR, China" },
  { value: "HUN", label: "Hungary" },
  { value: "ISL", label: "Iceland" },
  { value: "IND", label: "India" },
  { value: "IDN", label: "Indonesia" },
  { value: "IRN", label: "Iran" },
  { value: "IRQ", label: "Iraq" },
  { value: "IRL", label: "Ireland" },
  { value: "IMY", label: "Isle of Man" },
  { value: "ISR", label: "Israel" },
  { value: "ITA", label: "Italy" },
  { value: "JAM", label: "Jamaica" },
  { value: "JPN", label: "Japan" },
  { value: "JOR", label: "Jordan" },
  { value: "KAZ", label: "Kazakhstan" },
  { value: "KEN", label: "Kenya" },
  { value: "KIR", label: "Kiribati" },
  { value: "KOR", label: "Korea" },
  { value: "KSV", label: "Kosovo" },
  { value: "KWT", label: "Kuwait" },
  { value: "KGZ", label: "Kyrgyz Republic" },
  { value: "LAO", label: "Lao PDR" },
  { value: "LCN", label: "Latin America & Caribbean (all income levels)" },
  { value: "LAC", label: "Latin America & Caribbean (developing only)" },
  { value: "LVA", label: "Latvia" },
  { value: "LDC", label: "Least developed countries: UN classification" },
  { value: "LBN", label: "Lebanon" },
  { value: "LSO", label: "Lesotho" },
  { value: "LBR", label: "Liberia" },
  { value: "LBY", label: "Libya" },
  { value: "LIE", label: "Liechtenstein" },
  { value: "LTU", label: "Lithuania" },
  { value: "LMY", label: "Low & middle income" },
  { value: "LIC", label: "Low income" },
  { value: "LMC", label: "Lower middle income" },
  { value: "LUX", label: "Luxembourg" },
  { value: "MAC", label: "Macao SAR, China" },
  { value: "MKD", label: "Macedonia" },
  { value: "MDG", label: "Madagascar" },
  { value: "MWI", label: "Malawi" },
  { value: "MYS", label: "Malaysia" },
  { value: "MDV", label: "Maldives" },
  { value: "MLI", label: "Mali" },
  { value: "MLT", label: "Malta" },
  { value: "MHL", label: "Marshall Islands" },
  { value: "MRT", label: "Mauritania" },
  { value: "MUS", label: "Mauritius" },
  { value: "MEX", label: "Mexico" },
  { value: "FSM", label: "Micronesia" },
  { value: "MEA", label: "Middle East & North Africa (all income levels)" },
  { value: "MNA", label: "Middle East & North Africa (developing only)" },
  { value: "MIC", label: "Middle income" },
  { value: "MDA", label: "Moldova" },
  { value: "MCO", label: "Monaco" },
  { value: "MNG", label: "Mongolia" },
  { value: "MNE", label: "Montenegro" },
  { value: "MAR", label: "Morocco" },
  { value: "MOZ", label: "Mozambique" },
  { value: "MMR", label: "Myanmar" },
  { value: "NAM", label: "Namibia" },
  { value: "NPL", label: "Nepal" },
  { value: "NLD", label: "Netherlands" },
  { value: "NCL", label: "New Caledonia" },
  { value: "NZL", label: "New Zealand" },
  { value: "NIC", label: "Nicaragua" },
  { value: "NER", label: "Niger" },
  { value: "NGA", label: "Nigeria" },
  { value: "NAC", label: "North America" },
  { value: "MNP", label: "Northern Mariana Islands" },
  { value: "NOR", label: "Norway" },
  { value: "OED", label: "OECD members" },
  { value: "OMN", label: "Oman" },
  { value: "OSS", label: "Other small states" },
  { value: "PSS", label: "Pacific island small states" },
  { value: "PAK", label: "Pakistan" },
  { value: "PLW", label: "Palau" },
  { value: "PAN", label: "Panama" },
  { value: "PNG", label: "Papua New Guinea" },
  { value: "PRY", label: "Paraguay" },
  { value: "PER", label: "Peru" },
  { value: "PHL", label: "Philippines" },
  { value: "POL", label: "Poland" },
  { value: "PRT", label: "Portugal" },
  { value: "PRI", label: "Puerto Rico" },
  { value: "QAT", label: "Qatar" },
  { value: "ROM", label: "Romania" },
  { value: "RUS", label: "Russia" },
  { value: "RWA", label: "Rwanda" },
  { value: "WSM", label: "Samoa" },
  { value: "SMR", label: "San Marino" },
  { value: "SAU", label: "Saudi Arabia" },
  { value: "SEN", label: "Senegal" },
  { value: "SRB", label: "Serbia" },
  { value: "SYC", label: "Seychelles" },
  { value: "SLE", label: "Sierra Leone" },
  { value: "SGP", label: "Singapore" },
  { value: "SXM", label: "Sint Maarten (Dutch part)" },
  { value: "SVK", label: "Slovak Republic" },
  { value: "SVN", label: "Slovenia" },
  { value: "SST", label: "Small states" },
  { value: "SLB", label: "Solomon Islands" },
  { value: "SOM", label: "Somalia" },
  { value: "ZAF", label: "South Africa" },
  { value: "SAS", label: "South Asia" },
  { value: "SSD", label: "South Sudan" },
  { value: "ESP", label: "Spain" },
  { value: "LKA", label: "Sri Lanka" },
  { value: "KNA", label: "St. Kitts and Nevis" },
  { value: "LCA", label: "St. Lucia" },
  { value: "MAF", label: "St. Martin (French part)" },
  { value: "VCT", label: "St. Vincent and the Grenadines" },
  { value: "SSF", label: "Sub-Saharan Africa (all income levels)" },
  { value: "SSA", label: "Sub-Saharan Africa (developing only)" },
  { value: "SDN", label: "Sudan" },
  { value: "SUR", label: "Suriname" },
  { value: "SWZ", label: "Swaziland" },
  { value: "SWE", label: "Sweden" },
  { value: "CHE", label: "Switzerland" },
  { value: "SYR", label: "Syrian Arab Republic" },
  { value: "STP", label: "São Tomé and Principe" },
  { value: "TJK", label: "Tajikistan" },
  { value: "TZA", label: "Tanzania" },
  { value: "THA", label: "Thailand" },
  { value: "BHS", label: "The Bahamas" },
  { value: "GMB", label: "The Gambia" },
  { value: "TMP", label: "Timor-Leste" },
  { value: "TGO", label: "Togo" },
  { value: "TON", label: "Tonga" },
  { value: "TTO", label: "Trinidad and Tobago" },
  { value: "TUN", label: "Tunisia" },
  { value: "TUR", label: "Turkey" },
  { value: "TKM", label: "Turkmenistan" },
  { value: "TCA", label: "Turks and Caicos Islands" },
  { value: "TUV", label: "Tuvalu" },
  { value: "UGA", label: "Uganda" },
  { value: "UKR", label: "Ukraine" },
  { value: "ARE", label: "United Arab Emirates" },
  { value: "GBR", label: "United Kingdom" },
  { value: "USA", label: "United States" },
  { value: "UMC", label: "Upper middle income" },
  { value: "URY", label: "Uruguay" },
  { value: "UZB", label: "Uzbekistan" },
  { value: "VUT", label: "Vanuatu" },
  { value: "VEN", label: "Venezuela" },
  { value: "VNM", label: "Vietnam" },
  { value: "VIR", label: "Virgin Islands" },
  { value: "WBG", label: "West Bank and Gaza" },
  { value: "WLD", label: "World" },
  { value: "YEM", label: "Yemen" },
  { value: "ZMB", label: "Zambia" },
  { value: "ZWE", label: "Zimbabwe" },
];
