export const countries = [
  { value: "Islamic State of Afghanistan", label: "Afghanistan" },
  { value: "Republic of Albania", label: "Albania" },
  { value: "People's Democratic Republic of Algeria", label: "Algeria" },
  { value: "American Samoa", label: "American Samoa" },
  { value: "Principality of Andorra", label: "Andorra" },
  { value: "People's Republic of Angola", label: "Angola" },
  { value: "Antigua and Barbuda", label: "Antigua and Barbuda" },
  { value: "Arab World", label: "Arab World" },
  { value: "Argentine Republic", label: "Argentina" },
  { value: "Republic of Armenia", label: "Armenia" },
  { value: "Aruba", label: "Aruba" },
  { value: "Commonwealth of Australia", label: "Australia" },
  { value: "Republic of Austria", label: "Austria" },
  { value: "Republic of Azerbaijan", label: "Azerbaijan" },
  { value: "Kingdom of Bahrain", label: "Bahrain" },
  { value: "People's Republic of Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Republic of Belarus", label: "Belarus" },
  { value: "Kingdom of Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Republic of Benin", label: "Benin" },
  { value: "The Bermudas", label: "Bermuda" },
  { value: "Kingdom of Bhutan", label: "Bhutan" },
  { value: "Plurinational State of Bolivia", label: "Bolivia" },
  { value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina" },
  { value: "Republic of Botswana", label: "Botswana" },
  { value: "Federative Republic of Brazil", label: "Brazil" },
  { value: "Brunei Darussalam", label: "Brunei" },
  { value: "Republic of Bulgaria", label: "Bulgaria" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Republic of Burundi", label: "Burundi" },
  { value: "Republic of Cabo Verde", label: "Cabo Verde" },
  { value: "Kingdom of Cambodia", label: "Cambodia" },
  { value: "Republic of Cameroon", label: "Cameroon" },
  { value: "Canada", label: "Canada" },
  { value: "Caribbean small states", label: "Caribbean small states" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  { value: "Central African Republic", label: "Central African Republic" },
  {
    value: "Central Europe and the Baltics",
    label: "Central Europe and the Baltics",
  },
  { value: "Republic of Chad", label: "Chad" },
  { value: "Channel Islands", label: "Channel Islands" },
  { value: "Republic of Chile", label: "Chile" },
  { value: "People's Republic of China", label: "China" },
  { value: "Republic of Colombia", label: "Colombia" },
  { value: "Union of the Comoros", label: "Comoros" },
  { value: "Republic of Congo", label: "Congo" },
  { value: "Republic of Costa Rica", label: "Costa Rica" },
  { value: "Republic of Côte d'Ivoire", label: "Côte d'Ivoire" },
  { value: "Republic of Croatia", label: "Croatia" },
  { value: "Republic of Cuba", label: "Cuba" },
  { value: "Curaçao", label: "Curaçao" },
  { value: "Republic of Cyprus", label: "Cyprus" },
  { value: "Czech Republic", label: "Czech Republic" },
  {
    value: "Democratic People's Republic of Korea",
    label: "Dem. People's Rep. Korea",
  },
  { value: "Democratic Republic of the Congo", label: "Dem. Rep. Congo" },
  { value: "Kingdom of Denmark", label: "Denmark" },
  { value: "Republic of Djibouti", label: "Djibouti" },
  { value: "Commonwealth of Dominica", label: "Dominica" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  {
    value: "East Asia & Pacific (all income levels)",
    label: "East Asia & Pacific (all income levels)",
  },
  {
    value: "East Asia & Pacific (developing only)",
    label: "East Asia & Pacific (developing only)",
  },
  { value: "Republic of Ecuador", label: "Ecuador" },
  { value: "Arab Republic of Egypt", label: "Egypt" },
  { value: "Republic of El Salvador", label: "El Salvador" },
  { value: "Republic of Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "State of Eritrea", label: "Eritrea" },
  { value: "Republic of Estonia", label: "Estonia" },
  { value: "Federal Democratic Republic of Ethiopia", label: "Ethiopia" },
  { value: "Euro area", label: "Euro area" },
  {
    value: "Europe & Central Asia (all income levels)",
    label: "Europe & Central Asia (all income levels)",
  },
  {
    value: "Europe & Central Asia (developing only)",
    label: "Europe & Central Asia (developing only)",
  },
  { value: "European Union", label: "European Union" },
  { value: "Faeroe Islands", label: "Faeroe Islands" },
  { value: "Republic of Fiji", label: "Fiji" },
  { value: "Republic of Finland", label: "Finland" },
  { value: "Fragile situations", label: "Fragile and conflict affected situations" },
  { value: "French Republic", label: "France" },
  { value: "French Polynesia", label: "French Polynesia" },
  { value: "Gabonese Republic", label: "Gabon" },
  { value: "Georgia", label: "Georgia" },
  { value: "Federal Republic of Germany", label: "Germany" },
  { value: "Republic of Ghana", label: "Ghana" },
  { value: "Hellenic Republic", label: "Greece" },
  { value: "Greenland", label: "Greenland" },
  { value: "Grenada", label: "Grenada" },
  { value: "Guam", label: "Guam" },
  { value: "Republic of Guatemala", label: "Guatemala" },
  { value: "Republic of Guinea", label: "Guinea" },
  { value: "Republic of Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Co-operative Republic of Guyana", label: "Guyana" },
  { value: "Republic of Haiti", label: "Haiti" },
  {
    value: "Heavily indebted poor countries (HIPC)",
    label: "Heavily indebted poor countries (HIPC)",
  },
  { value: "High income", label: "High income" },
  { value: "High income: nonOECD", label: "High income: nonOECD" },
  { value: "High income: OECD", label: "High income: OECD" },
  { value: "Republic of Honduras", label: "Honduras" },
  {
    value: "Hong Kong Special Administrative Region of the People's Republic of China",
    label: "Hong Kong SAR, China",
  },
  { value: "Hungary", label: "Hungary" },
  { value: "Republic of Iceland", label: "Iceland" },
  { value: "Republic of India", label: "India" },
  { value: "Republic of Indonesia", label: "Indonesia" },
  { value: "Islamic Republic of Iran", label: "Iran" },
  { value: "Republic of Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "Isle of Man", label: "Isle of Man" },
  { value: "State of Israel", label: "Israel" },
  { value: "Italian Republic", label: "Italy" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Hashemite Kingdom of Jordan", label: "Jordan" },
  { value: "Republic of Kazakhstan", label: "Kazakhstan" },
  { value: "Republic of Kenya", label: "Kenya" },
  { value: "Republic of Kiribati", label: "Kiribati" },
  { value: "Republic of Korea", label: "Korea" },
  { value: "Republic of Kosovo", label: "Kosovo" },
  { value: "State of Kuwait", label: "Kuwait" },
  { value: "Kyrgyz Republic", label: "Kyrgyz Republic" },
  { value: "Lao People's Democratic Republic", label: "Lao PDR" },
  {
    value: "Latin America & Caribbean (all income levels)",
    label: "Latin America & Caribbean (all income levels)",
  },
  {
    value: "Latin America & Caribbean (developing only)",
    label: "Latin America & Caribbean (developing only)",
  },
  { value: "Republic of Latvia", label: "Latvia" },
  {
    value: "Least developed countries: UN classification",
    label: "Least developed countries: UN classification",
  },
  { value: "Lebanese Republic", label: "Lebanon" },
  { value: "Kingdom of Lesotho", label: "Lesotho" },
  { value: "Republic of Liberia", label: "Liberia" },
  { value: "Socialist People's Libyan Arab Jamahiriya", label: "Libya" },
  { value: "Principality of Liechtenstein", label: "Liechtenstein" },
  { value: "Republic of Lithuania", label: "Lithuania" },
  { value: "Low & middle income", label: "Low & middle income" },
  { value: "Low income", label: "Low income" },
  { value: "Lower middle income", label: "Lower middle income" },
  { value: "Grand Duchy of Luxembourg", label: "Luxembourg" },
  {
    value: "Macao Special Administrative Region of the People's Republic of China",
    label: "Macao SAR, China",
  },
  { value: "Former Yugoslav Republic of Macedonia", label: "Macedonia" },
  { value: "Republic of Madagascar", label: "Madagascar" },
  { value: "Republic of Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Republic of Maldives", label: "Maldives" },
  { value: "Republic of Mali", label: "Mali" },
  { value: "Republic of Malta", label: "Malta" },
  { value: "Republic of the Marshall Islands", label: "Marshall Islands" },
  { value: "Islamic Republic of Mauritania", label: "Mauritania" },
  { value: "Republic of Mauritius", label: "Mauritius" },
  { value: "United Mexican States", label: "Mexico" },
  { value: "Federated States of Micronesia", label: "Micronesia" },
  {
    value: "Middle East & North Africa (all income levels)",
    label: "Middle East & North Africa (all income levels)",
  },
  {
    value: "Middle East & North Africa (developing only)",
    label: "Middle East & North Africa (developing only)",
  },
  { value: "Middle income", label: "Middle income" },
  { value: "Republic of Moldova", label: "Moldova" },
  { value: "Principality of Monaco", label: "Monaco" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Kingdom of Morocco", label: "Morocco" },
  { value: "Republic of Mozambique", label: "Mozambique" },
  { value: "Republic of the Union of Myanmar", label: "Myanmar" },
  { value: "Republic of Namibia", label: "Namibia" },
  { value: "Nepal", label: "Nepal" },
  { value: "Kingdom of the Netherlands", label: "Netherlands" },
  { value: "New Caledonia", label: "New Caledonia" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Republic of Nicaragua", label: "Nicaragua" },
  { value: "Republic of Niger", label: "Niger" },
  { value: "Federal Republic of Nigeria", label: "Nigeria" },
  { value: "North America", label: "North America" },
  {
    value: "Commonwealth of the Northern Mariana Islands",
    label: "Northern Mariana Islands",
  },
  { value: "Kingdom of Norway", label: "Norway" },
  { value: "OECD members", label: "OECD members" },
  { value: "Sultanate of Oman", label: "Oman" },
  { value: "Other small states", label: "Other small states" },
  { value: "Pacific island small states", label: "Pacific island small states" },
  { value: "Islamic Republic of Pakistan", label: "Pakistan" },
  { value: "Republic of Palau", label: "Palau" },
  { value: "Republic of Panama", label: "Panama" },
  { value: "The Independent State of Papua New Guinea", label: "Papua New Guinea" },
  { value: "Republic of Paraguay", label: "Paraguay" },
  { value: "Republic of Peru", label: "Peru" },
  { value: "Republic of the Philippines", label: "Philippines" },
  { value: "Republic of Poland", label: "Poland" },
  { value: "Portuguese Republic", label: "Portugal" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "State of Qatar", label: "Qatar" },
  { value: "Romania", label: "Romania" },
  { value: "Russian Federation", label: "Russia" },
  { value: "Republic of Rwanda", label: "Rwanda" },
  { value: "Samoa", label: "Samoa" },
  { value: "Republic of San Marino", label: "San Marino" },
  {
    value: "Democratic Republic of São Tomé and Principe",
    label: "São Tomé and Principe",
  },
  { value: "Kingdom of Saudi Arabia", label: "Saudi Arabia" },
  { value: "Republic of Senegal", label: "Senegal" },
  { value: "Republic of Serbia", label: "Serbia" },
  { value: "Republic of Seychelles", label: "Seychelles" },
  { value: "Republic of Sierra Leone", label: "Sierra Leone" },
  { value: "Republic of Singapore", label: "Singapore" },
  { value: "Sint Maarten (Dutch part)", label: "Sint Maarten (Dutch part)" },
  { value: "Slovak Republic", label: "Slovak Republic" },
  { value: "Republic of Slovenia", label: "Slovenia" },
  { value: "Small states", label: "Small states" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Somali Democratic Republic", label: "Somalia" },
  { value: "Republic of South Africa", label: "South Africa" },
  { value: "South Asia", label: "South Asia" },
  { value: "Republic of South Sudan", label: "South Sudan" },
  { value: "Kingdom of Spain", label: "Spain" },
  { value: "Democratic Socialist Republic of Sri Lanka", label: "Sri Lanka" },
  { value: "St. Kitts and Nevis", label: "St. Kitts and Nevis" },
  { value: "St. Lucia", label: "St. Lucia" },
  { value: "St. Martin (French part)", label: "St. Martin (French part)" },
  {
    value: "St. Vincent and the Grenadines",
    label: "St. Vincent and the Grenadines",
  },
  {
    value: "Sub-Saharan Africa (all income levels)",
    label: "Sub-Saharan Africa (all income levels)",
  },
  {
    value: "Sub-Saharan Africa (developing only)",
    label: "Sub-Saharan Africa (developing only)",
  },
  { value: "Republic of the Sudan", label: "Sudan" },
  { value: "Republic of Suriname", label: "Suriname" },
  { value: "Kingdom of Swaziland", label: "Swaziland" },
  { value: "Kingdom of Sweden", label: "Sweden" },
  { value: "Switzerland", label: "Switzerland" },
  { value: "Syrian Arab Republic", label: "Syrian Arab Republic" },
  { value: "Republic of Tajikistan", label: "Tajikistan" },
  { value: "United Republic of Tanzania", label: "Tanzania" },
  { value: "Kingdom of Thailand", label: "Thailand" },
  { value: "Commonwealth of The Bahamas", label: "The Bahamas" },
  { value: "Republic of The Gambia", label: "The Gambia" },
  { value: "Democratic Republic of Timor-Leste", label: "Timor-Leste" },
  { value: "Republic of Togo", label: "Togo" },
  { value: "Kingdom of Tonga", label: "Tonga" },
  { value: "Republic of Trinidad and Tobago", label: "Trinidad and Tobago" },
  { value: "Republic of Tunisia", label: "Tunisia" },
  { value: "Republic of Turkey", label: "Turkey" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Turks and Caicos Islands", label: "Turks and Caicos Islands" },
  { value: "Tuvalu", label: "Tuvalu" },
  { value: "Republic of Uganda", label: "Uganda" },
  { value: "Ukraine", label: "Ukraine" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  {
    value: "United Kingdom of Great Britain and Northern Ireland",
    label: "United Kingdom",
  },
  { value: "United States of America", label: "United States" },
  { value: "Upper middle income", label: "Upper middle income" },
  { value: "Oriental Republic of Uruguay", label: "Uruguay" },
  { value: "Republic of Uzbekistan", label: "Uzbekistan" },
  { value: "Republic of Vanuatu", label: "Vanuatu" },
  { value: "República Bolivariana de Venezuela", label: "Venezuela" },
  { value: "Socialist Republic of Vietnam", label: "Vietnam" },
  { value: "Virgin Islands of the United States", label: "Virgin Islands" },
  { value: "West Bank and Gaza", label: "West Bank and Gaza" },
  { value: "World", label: "World" },
  { value: "Republic of Yemen", label: "Yemen" },
  { value: "Republic of Zambia", label: "Zambia" },
  { value: "Republic of Zimbabwe", label: "Zimbabwe" },
];
